accountapp/urls.py
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountLoginView, AccountLogoutView, AccountDetailView, \
    AccountUpdateView

app_name = "accountapp"

urlpatterns = [
    path("hello_world/", hello_world, name="hello_world"),


    path("create/", AccountCreateView.as_view(), name="create"),

    path("login/", AccountLoginView.as_view(), name="login"),

    path("logout/", AccountLogoutView.as_view(), name="logout"),

    path('detail/<int:pk>/', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', AccountUpdateView.as_view(), name='update'),
    path('update/<int:pk>/', AccountUpdateView.as_view(), name='update'),


]

articleapp/urls.py
from django.urls import path

from articleapp.views import TempView, ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, \
    ArticleListView

app_name = 'articleapp'



urlpatterns = [

    path('temp/', TempView.as_view(), name="temp"),
    path('list' , ArticleListView.as_view(), name="list"),
    path('create/', ArticleCreateView.as_view(), name="create"),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name="detail"),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name="update"),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name="delete"),

]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = "profileapp"

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('create/<int:pk>/', ProfileUpdateView.as_view(), name='update'),

]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscribeView, SubscriptionListView

app_name = 'subscribeapp'


urlpatterns = [

    path('sub/<int:pk>/', SubscribeView.as_view(), name='sub'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

techit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accountapp.views import hello_world

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),

    path( '', hello_world)

] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT,
)

accountapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Registration(models.Model):
    email = models.CharField(max_length=255, null=False)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Article(models.Model):
    image = models.ImageField(upload_to='article/', null=False)
    title = models.CharField(max_length=255, null=False)
    content = models.TextField(null=True)

    like = models.IntegerField(default=0)

    writer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

accountapp/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm


class AccountUpdateForm(ModelForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
        ]

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountapp.forms import AccountUpdateForm
from accountapp.models import Registration
from articleapp.models import Article
from subscribeapp.models import Subscription


# Create your views here.


def hello_world(request, HttpResponseRedirct=None):
    if request.method == "POST":
        email = request.POST.get('email')

        reg = Registration()
        reg.email = email
        reg.save()

        reg_all = Registration.objects.all()

        return HttpResponseRedirect(reverse("accountapp:hello_world"))

    reg_all = Registration.objects.all()

    temp = "건담쵝오!"
    return render(request, "accountapp/hello_world.html",
                  context={"temp": temp,
                           "red_all": reg_all})



class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy("accountapp:hello_world")
    template_name = "accountapp/create.html"



class AccountLoginView(LoginView):
    template_name = "accountapp/login.html"

class AccountLogoutView(LogoutView):
    pass


class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    template_name = "accountapp/detail.html"
    context_object_name = "target_user"
    paginate_by = 20

    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(writer=self.object)

        subscribed = Subscription.objects.filter(user=self.request.user, target_user=self.object)

        return super().get_context_data(object_list=object_list, subscribed=subscribed, **kwargs)



@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    context_object_name = "target_user"
    template_name = "accountapp/update.html"

    def get_success_url(self):
        return reverse("accountapp:detail",
                       kwargs={"pk": self.kwargs["pk"]})

class AccountDeleteView(DeleteView):
    model = User
    context_object_name = "target_user"
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = "accountapp/derete"

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}


{% block content %}

<div class="my-5 text-center">
    <div>
        <h1>
            SignUp
        </h1>
    </div>
    <div>
        <form action="{% url 'accountapp:create' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <bitton class="btn btn-warning rounded-pill px-4"
                    type="submit">
                Submit
            </bitton>

        </form>
    </div>
</div>


{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}


<div class="my-5 text-center">
    <div class="my-5">
        <h1>
            Quit : {{ terget_user.username }}
        </h1>
    </div>


    <div style="max-width: 900px; margin: auto">
        <form action="{% url 'accountapp:delete' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-danger rounded-pill px-4"
                    type="submit">
                Submit
            </button>

        </form>
    </div>
</div>


{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% load bootstrap4 %}


{% block content %}

<div class="my-5 text-center">
    <div>
        <img src="{{ target_user.profile.image.url }}"
         style="height: 15rem; width: 15rem; border-radius: 100rem; object-fit: cover;">

        {% if target_user.profile %}
        <h1>
            {{ target_user.profile.nickname }}
        </h1>
        <h1>
            {{ target_user.profile.message }}
        </h1>

        {% elif target_user == user %}
        <a href="{% url 'profileapp:create' %}">
            <h1>
                Create Profile
            </h1>
        </a>
        {% else %}
        <h1>
            Unknown
        </h1>
        {% endif %}
    </div>


    <div style="max-width: 900px; margin: auto">
        <div>
            {{ target_user.date_joined }}

        </div>

        {% if user == target_user %}
        <a href="{% url 'accountapp:update' pk=target_user.pk %}">
            <div class="btn btn-warning rounded-pill px-5 my-5">
                Update
            </div>
            </a>
            {% if target_user.profile %}
            <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
            <div class="btn btn-dark rounded-pill px-5 my-5">
                Update
            </div>
            </a>
            {% endif %}
        </a>
        {% else %}

        {% if not subscribed %}
        <a href="{% url 'subscribeapp:sub' pk=target_user.pk %}">
            <div class="btn btn-dark rounded-pill px-5 my-5">
                Subscribe
            </div>
        </a>
        {% else %}
        <a href="{% url 'subscribeapp:sub' pk=target_user.pk %}">
            <div class="btn btn-secondary rounded-pill px-5 my-5">
                Unsubscribe
            </div>
        </a>
        {% endif %}


        {% endif %}

    </div>


</div>

{% include 'list_fragment.html' with article_list=object_list %}

{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}


{% block content %}


<div style="text-align: center">

    <h2 style="font-family: 'Black Ops One', cursive;">
        Registration
    </h2>

    <div class="my-4">
        <form action="/accounts/hello_world/" method="post">
            {% csrf_token %}
            <div class="row mb-3" style="max-width: 900px; margin: auto;">
              <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Email</label>
              <div class="col-sm-10">
                <input type="email" name="email" class="form-control form-control-sm" id="colFormLabelSm" placeholder="col-form-label-sm">
              </div>
            </div>
            <button type="submit">
               Surmit
            </button>
        </form>
    </div>

    <div>
        {{ temp }}
    </div>

    <div>
        {% for reg in reg_all %}

            <p>
                {{ reg.email }}
            </p>

        {% endfor %}
    </div>
</div>
{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}


<div class="my-5 text-center">
    <div class="my-5">
        <h1>
            Login
        </h1>
    </div>


    <div style="max-width: 900px; margin: auto">
        <form action="{% url 'accountapp:login' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-warning rounded-pill px-4"
                    type="submit">
                Submit
            </button>

        </form>
    </div>
</div>


{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}

{% load bootstrap4 %}


{% block content %}

<div class="my-5 text-center">
    <div class="my-5">
        <h1>
            Account Info Update
        </h1>
    </div>


    <div style="max-width: 900px; margin: auto">
        <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-warning rounded-pill px-4"
                    type="submit">
                Submit
            </button>

        </form>
    </div>
</div>


{% endblock %}